apiVersion: v1
kind: Service
metadata:
  name: mdb
spec:
  type: ClusterIP
  selector:
    database: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: similarity-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    nlp: similarity